version: "3.9"

services:
  api:
    build: .
    container_name: emotion_api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./configs:/app/configs
    environment:
      - MLFLOW_TRACKING_URI=file:/app/mlruns
    depends_on:
      - mlflow
    restart: unless-stopped

  mlflow:
    image: python:3.10-slim
    container_name: mlflow_server
    working_dir: /app
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
    command: >
      bash -c "pip install mlflow==2.14.3 &&
               mlflow ui --backend-store-uri file:/app/mlruns --host 0.0.0.0 --port 5000"
    restart: unless-stopped